import = ["~/.config/alacritty/rose-pine-moon.toml"]
[font]
size = 12

[font.normal]
family = "JetBrainsMono Nerd Font"
# family = "BlexMono Nerd Font"
style = "Regular"

[window.dimensions]
columns= 133
lines= 40

[shell]
program = "/bin/bash"
args = ["--login","-c","tmux"]
